services:
  postgres:
    build:
      context: database
      dockerfile: Dockerfile
    image: pg:latest
    environment:
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DATABASE: ${DATABASE_NAME}
      PGDATA: ${PGDATA}
    ports:
      - "${DATABASE_PORT}:5432"
    container_name: "postgresql"
    volumes:
      - pg_data:${PGDATA}
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16


