services:
  postgres:
    build:
      context: database
      dockerfile: Dockerfile
    image: ninja666/pg:latest
    environment:
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: ${PGDATA}
      PGPORT: ${DATABASE_PORT}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    container_name: "postgres"
    volumes:
      - pg_data:${PGDATA}
    networks:
      - backend


  nestjs:
    build:
      context: .  
      dockerfile: Dockerfile  
    image: ninja666/nestjs-app:latest
    env_file:
      - prod.env  
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"  
    depends_on:
      - postgres 
    container_name: "nestjs-app"
    networks:
      - backend



volumes:
  pg_data:

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24


