services:
  postgres:
    build:
      context: .
      dockerfile: database/Dockerfile
    image: ghcr.io/vwency/nestjs-api/pg:b78c388
    environment:
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: ${PGDATA}
      PGPORT: ${DATABASE_PORT}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    container_name: "postgres"
    volumes:
      - pg_data:${PGDATA}
    networks:
      - backend


  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/vwency/nestjs-api/nest-api:b78c388
    env_file:
      - prod.env  
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"  
    depends_on:
      - postgres 
    container_name: "nestjs-app"
    networks:
      - backend



volumes:
  pg_data:

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24


